#!/usr/bin/env python
# -*- coding: utf-8 -*-

import signal
import sys
import os
import subprocess

FILE_NAME = 'temp-role.yml'

def clean():
    print 'finish run_roll'
    os.remove(FILE_NAME)

def signal_handler(signal, frame):
    clean()
    sys.exit(0)

# 最低限「command名 -i inventory role名」は必要なので4で判定
if len(sys.argv) < 4:
    print 'Usage: ./%s -i inventory [options] roll' % (sys.argv[0])
    print 'ansible-playbookを./%sに置き換えた形式' % (sys.argv[0])
    quit()

opts = sys.argv[1:-1]
role = sys.argv[-1].replace(".yml", "")
print "create temp playbook for %s" % (role)
yml = """
---
- hosts: {role_name}
  roles:
    - {role_name}
""".format(role_name=role)

with open(FILE_NAME, "w") as f:
    signal.signal(signal.SIGINT, signal_handler)
    f.write(yml)

ansible = "ansible-playbook %s %s" % (" ".join(opts), FILE_NAME)
print ansible
subprocess.call(ansible, shell=True)
clean()
